# Generated by Django 4.1.1 on 2022-09-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
