# Generated by Django 4.1.1 on 2022-09-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probas', '0002_person_first_name_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
